version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 10
  reviewers:
  - AuHau
  ignore:
  - dependency-name: peer-id
    versions:
    - 0.14.4
    - 0.14.6
    - 0.14.8
  - dependency-name: web3-utils
    versions:
    - 1.3.3
    - 1.3.5
  - dependency-name: web3-eth-contract
    versions:
    - 1.3.3
    - 1.3.4
    - 1.3.5
  - dependency-name: web3-eth
    versions:
    - 1.3.3
    - 1.3.4
    - 1.3.5
  - dependency-name: socket.io-client
    versions:
    - 3.1.2
    - 4.0.0
    - 4.0.1
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
  - dependency-name: "@fluffy-spoon/substitute"
    versions:
    - 1.185.0
    - 1.187.0
    - 1.193.0
  - dependency-name: sql-formatter
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: cids
    versions:
    - 1.1.5
  - dependency-name: sequelize
    versions:
    - 6.4.0
  - dependency-name: multicodec
    versions:
    - 2.1.0
